### ISSUE TITLE
Freezes when empty function exists

### ISSUE THREAD

**Issue by fithurriague** [akinsho/flutter-tools.nvim#308] opened 2023-11-14 14:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

# Freeze

```dart
somefunction() {
  Map willCouseBug = <String, dynamic>{};
  willCouseBug[] // <--  Not only does not show the brackets but FREEZES neovim when you type the first bracket
}

emptyFunction() {

}
```

# Does not freeze
```dart
somefunction() {
  Map willCouseBug = <String, dynamic>{};
  willCouseBug[] // <--  Now it does not freeze when you type the bracket
}

notEmptyFunction() {
  var foo;
  String bar = 'imstring';
}
```

### Expected Behavior

# Does not freeze

```dart
somefunction() {
  Map willCouseBug = <String, dynamic>{};
  willCouseBug[] // <--  Does not freeze when you type the bracket
}

emptyFunction() {

}
```

Being able to write the file scaffold without bugs, so you can organize it in your head.

### Steps To Reproduce

1. Create flutter app
2. Go to main.dart or any file
3. Write an empty function
4. Go anywhere above the empty function
5. Write a map
6. Try to map something with square brackets
7. Freezes

### Environment

```Markdown
- OS:
EndeavourOS Linux x86_64 

- Flutter version:
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (hace 3 semanas) • 2023-10-25 13:42:25
-0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0

- Is flutter in $PATH:
Yes

- neovim version:
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1699392533
```

**Comment by akinsho** [comment] 2023-11-15 10:46
@fithurriague can you confirm that this is not a treesitter issue vs. an lsp one, these sort of issues have historically been TS related

**Comment by fithurriague** [comment] 2023-11-15 12:33
> @fithurriague can you confirm that this is not a treesitter issue vs. an lsp one, these sort of issues have historically been TS related

Well, uninstalling the plugin solved the problem...but I can double check and let you know if you like.

**Comment by phelipe** [comment] 2023-11-22 16:08
> > @fithurriague can you confirm that this is not a treesitter issue vs. an lsp one, these sort of issues have historically been TS related
> 
> Well, uninstalling the plugin solved the problem...but I can double check and let you know if you like.

Try locking the version of treesitter to the commit with hash '33eb472b459f1d2bf49e16154726743ab3ca1c6d'. This solves a lot of problems here.

```
    commit = '33eb472b459f1d2bf49e16154726743ab3ca1c6d',
```

**Comment by akinsho** [comment] 2023-11-22 16:50
I'm going to close this out since the issue is ostensibly treesitter which this plugin isn't related to/responsible for

**Closed by akinsho** 2023-11-22 16:50 UTC
