### ISSUE TITLE
[BUG] Color visualizer not working

### ISSUE THREAD

**Issue by JPFrancoia** [akinsho/flutter-tools.nvim#301] opened 2023-10-14 11:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The square icon doesn't show the actual color.

![screen-2023-10-14-12-34-20](https://github.com/akinsho/flutter-tools.nvim/assets/2399090/3188df5b-c444-489d-b90d-0e0c4577194c)

![screen-2023-10-14-12-36-12](https://github.com/akinsho/flutter-tools.nvim/assets/2399090/4729889d-4134-440b-8cae-95139675cc23)

### Expected Behavior

The square icon should show the corresponding color

### Steps To Reproduce

I just have this configured for the plugin:

```
lua <<EOF
vim.diagnostic.disable()
require("flutter-tools").setup {
  widget_guides = {
    enabled = true,
  },
  closing_tags = {
    enabled = false
  },
  lsp = {
    color = {
      enabled = true,
      background = false, 
      foreground = false, 
      virtual_text = true, 
      virtual_text_str = "■",
    }
  }
}
EOF
```

### Environment

```Markdown
- OS: Archlinux
- Flutter version: Flutter 3.13.6 • channel stable • https://github.com/flutter/flutter.git
- Is flutter in $PATH: yes
- neovim version: NVIM v0.9.4
```

### Anything else?

There was a similar ticket: https://github.com/akinsho/flutter-tools.nvim/issues/203. I read it and tried the proposed solutions, but it didn't work.

**Comment by akinsho** [comment] 2023-10-18 13:03
Seems to work for me without issue but could be down to any number of things. Personally haven't got time to go digging. @sidlatau are you able to see colours in your projects? if so I think we need a more specific root cause there's not enough people around to go digging into stuff like this without more specific root cause issues.

**Comment by sidlatau** [comment] 2023-10-18 14:07
I also can not reproduce it, colors are shown for me:
<img width="498" alt="image" src="https://github.com/akinsho/flutter-tools.nvim/assets/4973296/b9000e17-70dc-4756-a884-47a495c99544">

**Comment by akinsho** [comment] 2023-10-19 10:12
@JPFrancoia unfortunately I really just don't have any time to dig in to this at all. I'd suggest maybe starting by looking at your LSP logs. This isn't specific to this plugin and there should be references for this online/maybe help docs about checking nvim's lsp logs. Also I'd try with a minimal init.lua without all your other plugins just inside a dart file with colours and only this plugin and see what happens.

I'm going to close this out since realistically neither @sidlatau or I will have time to walk through your setup and I think it will come down to some specific part of your config or setup. If you find something that indicates a bug in this plugin though not unique to your setup please post back here

**Closed by akinsho** 2023-10-19 10:12 UTC
