### ISSUE TITLE
[BUG] Neovim Freezes 

### ISSUE THREAD

**Issue by Pratham16112002** [akinsho/flutter-tools.nvim#267] opened 2023-06-20 04:37 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

When I am editing a dart file , press Enter i.e ( <CR> )  key my whole neovim gets halt for a second , this does not occur every time I press enter but most of the time . This is issue is only persist in the dartls 

https://github.com/akinsho/flutter-tools.nvim/assets/90999700/410f9ff5-10b2-4a96-b8c3-84f1aeb8f589

Also : After the neovim freezes and I can continuously press enter without any issue.  

### Expected Behavior

When I should press the enter key the neovim should never get halt , with .dart files 

https://github.com/akinsho/flutter-tools.nvim/assets/90999700/973a497a-d880-4ce4-8646-83c31e775885

In the above video enter key is working fine without any error , To be precise I am editing a pubspec.lock file 

### Steps To Reproduce

[issue_log.txt](https://github.com/akinsho/flutter-tools.nvim/files/11795926/issue_log.txt)
Attaching some logs that might make the issue more  clearer 

### Environment

```Markdown
- OS:Manjaro Linux x86_64 
- Flutter version: 3.10.3 
- Is flutter in $PATH: Yes
- neovim version: 0.9.0
```

### Anything else?

![image](https://github.com/akinsho/flutter-tools.nvim/assets/90999700/b924e1cd-093e-49f8-984b-32f91eb94be6)
LSP info SS 
#248 
This timeout issue looks similar to mine but I tried everything still nothing worked . 
`"server_request: callback result"	{  result = vim.NIL,  status = true}`  
Saw this log in  my log history .

**Comment by nav-28** [comment] 2023-06-26 02:19
I am having the same issue. I have tried a bare bones config and still get the error. Also, this only happens with dartls

**Comment by akinsho** [comment] 2023-06-29 09:23
> I am having the same issue. I have tried a bare bones config and still get the error. Also, this only happens with dartls

@nav-28 can you please confirm what a barebones config means in this case. Are you still using a configuration framework? can you please include precisely what minimal `init.lua` setup you are using that reliably reproduces this issue.

**Comment by nav-28** [comment] 2023-06-30 03:52
> > I am having the same issue. I have tried a bare bones config and still get the error. Also, this only happens with dartls
> 
> @nav-28 can you please confirm what a barebones config means in this case. Are you still using a configuration framework? can you please include precisely what minimal `init.lua` setup you are using that reliably reproduces this issue.

Oh I was using LazyVim. Although I have not been able to recreate it. I redid my config and removed unused plugins and something fixed it. Sorry, I couldn't catch what was causing the issue.

**Comment by akinsho** [comment] 2023-06-30 06:46
Ok closing this out since it's reproducible with a minimal configuration

**Closed by akinsho** 2023-06-30 06:46 UTC

**Comment by zinahe** [comment] 2023-07-02 16:44
Hi,
I am also having this same exact issue. But I was able to isolate it and make it work. The freeze happens if you have nvim-treesitter configured to handle indentation. I'm guessing there is a conflict between **nvim-treesitter** and **flutter-tools** trying to handle what happens when the ENTER key is pressed.

Adding the following in my nvim-treesitter configuration fixed the issue:
```
indent = {
	enable = true,

	-- NOTE: enabling indentation significantly slows down editing in Dart files
	disable = {'dart'}
}
```

Hope that helps.
