### ISSUE TITLE
flutteroutline error

### ISSUE THREAD

**Issue by truongtd94** [akinsho/flutter-tools.nvim#226] opened 2023-03-29 10:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This error appears when i press 'a' key in outline panel, I want to enable codeaction in outline but can't. Please suggest and fix this error, thanks a lot.

### Expected Behavior

this error appears when i press 'a' key in outline panel, i want to enable codeaction in outline but can't. Please suggest and fix this error, thanks a lot.
[ Image error ]
https://github.com/truongtd94/errors/blob/master/2022222.png
https://github.com/truongtd94/errors/blob/master/1111.png

### Steps To Reproduce

1. open flutter outline
2. press 'a' key in widge outline panel
3. show error

### Environment

```Markdown
- OS:
- Flutter version:
- Is flutter in $PATH:
- neovim version:
```

**Comment by akinsho** [comment] 2023-03-29 11:09
Hi @truongtd94

I really need a clearer breakdown of what you are reporting. I was able to reproduce the earlier issue you mentioned and pushed a fix. I know there are still some issues to work on but I can't tell what this issue is actually reporting since it's just the exact same as before with no changes.

**Closed** 2023-03-29 11:15 UTC
