### ISSUE TITLE
[Bug]: not an editor command FlutterOutlineOpen and FlutterOutlineToggle

### ISSUE THREAD

**Issue by samuelnihoul** [akinsho/flutter-tools.nvim#211] opened 2023-02-25 12:55 UTC
I am on a fresh install with blank config. I get these 2 errors when I try either way of opening the outline.

**Comment by akinsho** [comment] 2023-02-25 13:19
@samuelnihoul without any information about your setup at all I have no idea how to help. How have you installed he plugins? how have you verified that the plugin is actually loaded etc? Based on the limited information here I think it's safe to say that you haven't loaded the plugin since by default these commands are added *granted you are actually in a dart file* there is no point calling these functions outside of a dart file and this plugin won't even load if your not at least in a dart file

**Comment by samuelnihoul** [comment] 2023-02-25 18:43
Here is my plugins/init.lua:
```
local plugins = {
['nvim-lua/plenary.nvim']={},
['akinsho/flutter-tools.nvim']={}
}

-- Load all plugins
local present, packer = pcall(require, "packer")

if present then
  vim.cmd "packadd packer.nvim"

  -- Override with default plugins with user ones
  plugins = require("core.utils").merge_plugins(plugins)



  packer.init()
  packer.startup { plugins }
end
```
I am in a Dart file when I try the commands.

**Comment by samuelnihoul** [comment] 2023-02-25 18:48
My full minimum reproducible example can be found on the github samuelnihoul/nvchad branch test.

**Comment by samuelnihoul** [comment] 2023-02-25 18:50
It is basically a clean NVChad install where I deleted all the plugins and put only yours and nvim-lua/plenary.nvim.

**Comment by samuelnihoul** [comment] 2023-02-25 18:50
I also deleted the packer options part.

**Comment by akinsho** [comment] 2023-02-25 18:59
@samuelnihoul this isn't a normal neovim minimal configuration, using nvchad to reproduce an issues isn't really valid since that is not a clean neovim environment. I highly recommend you try neovim without all of that and just put the plugin somewhere you can `packadd` it and jsut see if that works between packer and nvchad any number of things could be going wrong. Digging through those separate tools and how their setup and affecting this plugin isn't really my remit. I can verify locally that this plugin works as expected when loaded correctly so in all likelihood this issue is with your config.

**Comment by samuelnihoul** [comment] 2023-02-26 06:37
OK sorry

**Comment by akinsho** [comment] 2023-02-26 09:54
Closing, but if you get a working minimal reproduction (without things like nvchad) please post here.

**Closed by akinsho** 2023-02-26 09:54 UTC
